title: activity
description: Perform bulk server command execution and validations over ssh in an organised and efficient way.
google_analytics: 
show_downloads: true
theme: jekyll-theme-hacker

gems:
          - jekyll-mentions
